### ISSUE TITLE
Check if subscription already exists

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/FiLiP#137]
I would like to avoid posting duplicate subscriptions. 
I've already written a working function for this:

```python
# Get existing subs
subscription_list = cb_client.get_subscription_list()
# Build a new one
subscription = Subscription(**my_data)
# Only post if it not exists already:
if not subscription_already_exists(subscription, existing_subscriptions=subscription_list):
    logger.info("Posting new subscription: %s", subscription.json(indent=2))
    cb_client.post_subscription(subscription=subscription)
```

The function `subscription_already_exists`:

```python
def subscription_already_exists(subscription, existing_subscriptions):
    sub = subscription.dict(exclude={"id"}).copy()
    for _existing_sub in existing_subscriptions:
        ex_sub = _existing_sub.dict(exclude={"id"}).copy()
        equals = sub_dict_is_equal(ex_sub, sub)
        if equals:
            return True
    return False  # If still here, it's not in the list


def sub_dict_is_equal(first, second):
    if first.keys() != second.keys():
        logger.warning(
            "Subscriptions contain a different set of fields. "
            "Only comparing to new fields of the new one."
        )
    for k, v in first.items():
        ex_value = second.get(k, None)
        if isinstance(v, dict):
            equal = sub_dict_is_equal(v, ex_value)
            if equal:
                continue
            else:
                return False
        if not v:
            ex_value = bool(ex_value)
            v = bool(v)
        if v != ex_value:
            return False
    return True

```

The nasty recursive comparison is due to filip and fiware interaction. Empty attributes in the notification dict are sometimes None and sometimes `[]`. Without this, the feature would be even shorter.

I would opt to move the function to `post_subcription` and add a kwarg `check_duplicate` or some better fitting name.

**Comment by tstorek** [comment]
@FWuellhorst the ContextBrokerClient actually already supports such functionality already. In its `post_subscription` function.
What happens here is that before a subscription is sent the client checks if a matching subscription may already exist. You might be right that the implemented mechanism is rather simple and does not cover enough cases. We are happy about a pull request on this. Your version is slightly more efficient. Nevertheless, I would suggest adding a pattern matching method to the check of the subject. The current imlementation only checks complete matching of the subject and the notifcation part of a subscription. Maybe this is not enough for more advanced applications.

**Comment by FWuellhorst** [comment]
@djs0109 : FYI: The CI is currently running twice, as the mirror settings include push and pull request webhooks. 
![image](https://user-images.githubusercontent.com/22442514/220949917-81078c79-d38b-484a-a3ac-096880a1396b.png)
Is this wanted? If not, I could change it to push commit only.

**Comment by djs0109** [comment]
@FWuellhorst Good that you have noticed this issue! I can also see that the CI has been triggered twice for every commit. That will be great, if you can change it. But do you know what exactly trigger the other CI? Because for example I see that pipline [#923849](https://git.rwth-aachen.de/EBC/EBC_all/github_ci/FiLiP/-/pipelines/923849) is linked in the PR, but the other same CI [#923850](https://git.rwth-aachen.de/EBC/EBC_all/github_ci/FiLiP/-/pipelines/923850) is not linked in this Repo.

**Comment by FWuellhorst** [comment]
I would opt to use only pushes, same as in AixLib or other repos of ours. 

I can't seem to debug why my test is failing. How can I run them locally?
