### ISSUE TITLE
Get all subscriptions for an entity

### ISSUE THREAD

**Issue by sbanoeon** [RWTH-EBC/FiLiP#141]
**Is your feature request related to a problem? Please describe.**
The goal is to retrieve a list of subscriptions corresponding to entity id and entity type.

**Describe the solution you'd like**
The function "get_subscriptions_by_entity" would return subscriptions of which entity_id matches the passed id AND entity_type matches the passed type (also based on id and type pattern flags).

**Comment by tstorek** [comment]
@sbanoeon I think that this is related to #137 I suggest to add a function like 
`def is_subset(self, other)` to the subscription subclass `EntityPattern`. This would also help for detecting if a subscription might be already covered by another subscription. Anyway from  the API specs. one would always need to get the whole subscription list first, I think. @FWuellhorst what do you think about combining these two by adding `__eq__` to he models where possible and the proposed function where patterns may be required , 

Anyway I am happy about pull requests. @sbanoeon please check on the other pull requests :)

Thanks!

**Comment by tstorek** [comment]
@FWuellhorst i am fine with using the word matches or equals. The advantage of __eq__ is the automatic recursive calling. I am fine with both i think. Anyway i like it better than having a utility for this :)
