### ISSUE TITLE
Timeout for get request

### ISSUE THREAD

**Issue by djs0109** [RWTH-EBC/FiLiP#146]
**Describe the bug**
I am trying to make GET requests continuously. Filip starts every time a new HTTP connection before sending the request. The problem is that it sometimes gets stacked after creating a new connection (see the screenshot). The problem is very similar to this [issue](https://github.com/urllib3/urllib3/issues/1535) in urllib3

**Expected behavior**
I will expect an error, like a time-out error.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/101181614/169556590-8ac85a58-7959-4ef8-881b-5ded5546d159.png)

**Comment by djs0109** [comment]
I suppose we can add a default timeout here
https://github.com/RWTH-EBC/FiLiP/blob/d24f47daa272a65ccf9c92522374bc5228b9a3d1/filip/clients/base_http_client.py#L181-L183

**Comment by tstorek** [comment]
@djs0109 usually, urllib3 is handling this issue quite. Please also look into the server settings.
If the server closes the connection your client needs to open the connection every time. 

Do you reuse your clients? Please try again by using sessions that should maybe help as well.  

https://github.com/RWTH-EBC/FiLiP/blob/master/examples/basics/e01_http_clients.py

Please, also check on this one:

https://stackoverflow.com/questions/25239650/python-requests-speed-up-using-keep-alive

**Comment by djs0109** [comment]
I post my old and new code block here, and close this issue
old:
```python
# Create orion context broker 
self.ORION_CB = ContextBrokerClient(url=self.cb_url, fiware_header=fiware_header)
```
new:
```python
# Create orion context broker 
s = requests.Session()
self.ORION_CB = ContextBrokerClient(url=self.cb_url, fiware_header=fiware_header, session=s)
```
