### ISSUE TITLE
make models created by the utils.model_generator.create_data_model_file inherit from ContextEntity

### ISSUE THREAD

**Issue by sjohnen** [RWTH-EBC/FiLiP#162]
At the moment when creating a model based of a json schema, the resulting model does not inherit from `ContextEntity`.       

As far as I'm concerned adding the import path as string, as described the by the underlying [datamodel-code-generator library](https://koxudaxi.github.io/datamodel-code-generator/), when calling the according [function](https://github.com/RWTH-EBC/FiLiP/blob/master/filip/utils/model_generation.py#L81) inside FiLiP's wrapper function, should solve this problem:
```
generate(input_=schema, input_file_type=schema_type, output=output, class_name=class_name, 
base_class="filip.models.ngsi_v2.context.ContextEntity")
```

EDIT:
A different approach might be to allow the user to pass kwargs to `utils.model_generator.create_data_model_file` and and just unpack them in the generate function of datamodel-code-generator. In this case the user could pass the `base_class="filip.models.ngsi_v2.context.ContextEntity"` as kwarg via the wrapper function `utils.model_generator.create_data_model_file`, in addition to more custimization options!

It might look like:
```
generate(input_=schema, input_file_type=schema_type, output=output, class_name=class_name, **kwargs)
```

**Comment by tstorek** [comment]
@sjohnen thanks for this hint. Since, you assigned this to yourself. Is there any progress on this? Otherwise I propose to use your first approach for now and later raise another issue if required

**Comment by sjohnen** [comment]
I'm still trying to figure out a decent way to create a `ContextEntity` based on the parsed pydantic model! Simply inheriting from ContextEntity via the `base_class` attribute does not solve the problem. This is due to limitations in the underlying `datamodel_code_generator` library. 
I found two major issues:
1. Every class object created in the resulting file will inherit from `ContextEntity`, this may include classes that are considered attributes which should inherit from `ContextAttribute` instead. 
2. When the datamodel (i.e. json-schema) does define a field type (which is commonly done with the FiwareSmartDatamodels) it will overload the type field from the FiLiP `ContextEntity` pydantic class and lead to problems regarding the according validator.

It might be possible to inherit from `ContextEntityCV` but I'm not sure about limitations coming with this approach. I'm currently trying to recursively parse the generated pydantic model into a dict that can be used to instance a `ContextEntity` via dict-unpacking. But in this case one loses any additional validators like regex on strings and min and max values, making the whole idea of parsing a json-schema into the pydantic class pointless...

P.S.: I did not assign the issue to myself! You did, at least according to this thread!

**Comment by sjohnen** [comment]
After quite some time I'm pretty certain simply using inheritance from ContextEntity ist not possible with the current state of the `datamodel_code_generator`. Even the inheritance from ContextEntityCV does not pose simple. The models have to be defined a very specific way for it to work.
I would recommend closing this issue, since implementing this feature in a robust and reliable way is not just a "small" util but a whole library in of itself!

**Comment by djs0109** [comment]
I totally agree with you. Converting `JSON-schema` to `ContextEntity` is a big issue. We are trying to make some very specific implementation in our UI (check https://github.com/N5GEH/n5geh.tools.entirety/pull/110). Though it is currently still under implementation, I think it is difficult to migrate the full implementation later there back to `FiLiP`, because `FiLiP` as an API library is designed to be generic.
