### ISSUE TITLE
Validation on measurement transformation language

### ISSUE THREAD

**Issue by tstorek** [RWTH-EBC/FiLiP#165]
**Is your feature request related to a problem? Please describe.**
Currently, the measurement transformation language provided in the iot agents is not validated.

**Describe the solution you'd like**
When a device configuration is invoked or changed by a user the device model should check if the expression language is used in a consistant way. We can use pydantic validators for this.
 As FIWARE recommends using JEXL I suggest trying the pyjexl package for validation.

**Additional context**

- [Add any other context or screenshots about the feature request here.](https://iotagent-node-lib.readthedocs.io/en/2.12.0/expressionLanguage/index.html#measurement-transformation-expression-language)
- https://pypi.org/project/pyjexl/

**Comment by djs0109** [comment]
merged in #260
