### ISSUE TITLE
Set default service name to '' in tests default config

### ISSUE THREAD

**Issue by windrad6** [RWTH-EBC/FiLiP#166]
To more easily debug with the browser it might help to set the default service name to ''. That way no special headers are needed to read the full entity list of the local test fiware platform.

# create service paths for multi tenancy scenario and concurrent testing
FIWARE_SERVICE: str = Field(default='',
                            env=['FIWARE_SERVICE'])

**Comment by djs0109** [comment]
There are already default `service` and `service_path` in the data model:
https://github.com/RWTH-EBC/FiLiP/blob/4d888fa33b99e6c604883c9b494d1fdbf8727c48/filip/models/base.py#L102
https://github.com/RWTH-EBC/FiLiP/blob/4d888fa33b99e6c604883c9b494d1fdbf8727c48/filip/models/base.py#L109
