### ISSUE TITLE
Change does_entity_exists create error message if entity does not exist

### ISSUE THREAD

**Issue by windrad6** [RWTH-EBC/FiLiP#167]
The does_entity_exists function is directly calling the get_entity function. If entity does not exists this function will fail and create an error message. The expected behavior would not be an error message when probing for existing element.

**Comment by tstorek** [comment]
@windrad6 I checked on this. The function's response is correct, but the log is misleading if the entity does not exist. Probably, it is easier and cleaner to write an extra request for this, right?
