### ISSUE TITLE
Inconsistent use if entity_type parameter

### ISSUE THREAD

**Issue by windrad6** [RWTH-EBC/FiLiP#168]
**Describe the bug**
The parameter entity_type is used inconsistently in different functions in cb.py. For get_entity_attributes it is an optional parameter, whereas for delete_entity it is a required parameter. It should either be one or the other. Since one could argue that fiware requires the combination of entity_id and entity_type to be unique, both should be required in all functions that access an entity. On the other hand, always providing an entity_type leads to unnecessary code complexity and could in a lot of cases be dismissed. 

http://fiware.github.io/specifications/ngsiv2/stable/

"Context EntitiesContext entities, or simply entities, are the center of gravity in the FIWARE NGSI information model. An entity represents a thing, i.e., any physical or logical object (e.g., a sensor, a person, a room, an issue in a ticketing system, etc.). Each entity has an entity id.Furthermore, the type system of FIWARE NGSI enables entities to have an entity type. Entity types are semantic types; they are intended to describe the type of thing represented by the entity. For example, a context entity with id sensor-365 could have the type temperatureSensor.Each entity is uniquely identified by the combination of its id and type."

**Comment by tstorek** [comment]
@windrad6 Thanks for reporting. Hence, what do you suggest? I think that the entity_type ist always left optional if not necessarily required by the API. As you said we tried to keep it as simple as possible.
