### ISSUE TITLE
Missing "autoprovision" in "ServiceGroup" in models/ngsi_v2/iot.py

### ISSUE THREAD

**Issue by orange95** [RWTH-EBC/FiLiP#17]

**Comment by tstorek** [comment]
@orange95 please provide a full description of the issue. Additionally, please provide the link to the specification if possible.

**Comment by orange95** [comment]
In the class "ServiceGroup", there should be an attribute called "autoprovision". When not using FiLiP, it is able to set the "autoprovision" of a service group, so it should also be possible to be done via FiLiP.

https://github.com/RWTH-EBC/FiLiP/blob/d274de0902878c6036398701298e3b7b54b46765/filip/models/ngsi_v2/iot.py#L176-L271
