### ISSUE TITLE
Error on duplicate object_id

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/FiLiP#178]
**Is your feature request related to a problem? Please describe.**
If a device as two attrs with the same object_id, fiware would randomly send the value to only one attr.

**Describe the solution you'd like**
Warn / throw errors in that case for a device-config.

**Comment by djs0109** [comment]
Good points! However, regarding the latest function that iotagent provides check [here](https://github.com/telefonicaid/iotagent-node-lib/blob/ad90059d58a6c85b282547812dd0cd7ee01b97b6/doc/api.md#multientity-support), I would even suggest that the `name` of attrs can be duplicated but the `object_id` must be unique

**Comment by djs0109** [comment]
@tstorek what is your opinion on this?

**Comment by djs0109** [comment]
Refactor plan:
- [ ] Not require `object_id  `
- [ ] If `object_id `is given, it should be unique 
- [ ] Device attribute `name` must not be unique
