### ISSUE TITLE
Possible bug in Filip's typePattern validation.

### ISSUE THREAD

**Issue by richardmarston** [RWTH-EBC/FiLiP#179]
https://github.com/RWTH-EBC/FiLiP/blob/master/filip/models/ngsi_v2/base.py#L48

It says that you can only specify a type pattern if you haven't specified an **entity** id.

```python
if values['type'] or values.get('typePattern', None):
    assert ((values['type'] and not values['typePattern']) or
                 (not values['id'] and values['typePattern'])), \
                "Type or pattern of the affected entities. " \
                "Both cannot be used at the same time."
```

I would have expected it to enforce that you can only specify a type pattern if you haven't specified a **type** id.

```python
if values['type'] or values.get('typePattern', None):
    assert ((values['type'] and not values['typePattern']) or
                 (not values['type'] and values['typePattern'])), \             # change is on this line
                "Type or pattern of the affected entities. " \
                "Both cannot be used at the same time."
```

Sorry if you are already aware or I am wrong.

**Comment by djs0109** [comment]
Yes, I think you are right. Could you assign yourself and fix that?

**Comment by richardmarston** [comment]
> Yes, I think you are right. Could you assign yourself and fix that?

I don't have write access / collaborator status in this repository. I can make a fork, but I can't create a branch to fix the defect in.
