### ISSUE TITLE
cb_client.post_subscription creates a new subscription even if the subscription already exists

### ISSUE THREAD

**Issue by lidiawestphal** [RWTH-EBC/FiLiP#181]
**Describe the bug**
cb_client.post_subscription() creates a new subscription unnecessarily because the if-clause in the line 1167 of the cb.py does not work properly.
`if sub_hash == ex_sub.json(include={'subject', 'notification'}):`
The error lies in the Notification model's default value for` "attrs":` the Notification-model puts there a `null`-value but the subscriptions returned from the OCB contain an empty list `[]`.

**To Reproduce**
1. Create and post e.g. a type-subscription for QL.
2. Create and post the same subscription again.
3. You will have two subscriptions in the OCB.

**Expected behavior**
A second subscription should not be created.

**Comment by tstorek** [comment]
@lidiawestphal thanks for reporting. This connected to #137 and will be fixed once #138
