### ISSUE TITLE
Python version upgrade to 3.10, 3.11, (3.12)

### ISSUE THREAD

**Issue by djs0109** [RWTH-EBC/FiLiP#211]
Currently, the community tends to use python `3.10`, `3.11`, and even `3.12` (see #209 #207 ). But `filip` can now officially only support python `3.7` - `3.9`. Therefore, an upgrade should be carefully taken to extend the python compatibility of `filip`

ToDos:
- [ ] Check `requirement.txt ` carefully and make certain adjustment, e.g. `igraph `
- [ ] Setup the test environment for Unitest in CI/CD, make sure all test cases can pass
- [ ] Add information in `README`, maybe on the header

**Comment by RCX112** [comment]
Checking all test cases after Issue #238 is fixed
