### ISSUE TITLE
Patch device leads to device already exists.

### ISSUE THREAD

**Issue by SBlechmann** [RWTH-EBC/FiLiP#219]
According to msh, there is an error when you try to patch a device. It says that the corresponding device already exists.

`Reason: {"name":"DUPLICATE_DEVICE_ID","message":"A device with the same pair (Service, DeviceId) was found:sensor001"}`

**Comment by djs0109** [comment]
Could you also provide a simple script for reproducing the error? It could just include device provision and device update. But actually, the functionality to patch device is always tested [here](https://github.com/RWTH-EBC/FiLiP/blob/f5f1d9fd4431b68d806e42cd494c00ad887c312e/tests/clients/test_ngsi_v2_iota.py#L302C33-L302C33)

**Comment by djs0109** [comment]
@SBlechmann Is there any update on this report?
