### ISSUE TITLE
Update contributing details

### ISSUE THREAD

**Issue by WaltherTrgovac** [RWTH-EBC/FiLiP#244]
**Is your feature request related to a problem? Please describe.**
Contributing instructions are outdated.

**Describe the solution you'd like**
We should add convention for the committing style.
Example 1: https://www.conventionalcommits.org/en/v1.0.0/
Example 2: https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines

**Comment by Maghnie** [comment]
@djs0109 What do you think? And should we use the convention used by Angular? 

Defining at least a couple of commit formulation conventions (e.g., `chore` and `docs`) in the contributing details would be helpful for the seamless integration of new FiLiP developers. :)

**Comment by djs0109** [comment]
@Maghnie yes, it is indeed meaningful. One direct use case will be the semantic-release tool. I think the one suggested by `conventionalcommits.org` is a good start. Our developers also had experience with it.
