### ISSUE TITLE
ngsi_v2 tutorials are deprecated

### ISSUE THREAD

**Issue by WaltherTrgovac** [RWTH-EBC/FiLiP#255]
**Describe the bug**
ngsi_v2 tutorials consist of exercises and solutions. Solutions use methods that are deprecated (pydantic and json methods).

**To Reproduce**
Executing exercise 3 solutions to exercise 7 produces various errors.

**Expected behavior**
Solutions should run properly.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**
Mostly TypeErrors are causing the errors that are easy to fix. There are also some PEP 8 errors occuring.

**Comment by WaltherTrgovac** [comment]
I am running into problems at exercise 5. There is a method imported from pydantic called `parse_file_as`. This method does not exist in version 2 of pydantic anymore. What I tried to do is use the method `validate_python`. This method takes a loaded json file as a parameter. I have done that, but then I keep running into other errors that might be connected to the deprecated method.

**Comment by WaltherTrgovac** [comment]
> I am running into problems at exercise 5. There is a method imported from pydantic called `parse_file_as`. This method does not exist in version 2 of pydantic anymore. What I tried to do is use the method `validate_python`. This method takes a loaded json file as a parameter. I have done that, but then I keep running into other errors that might be connected to the deprecated method. Here is the [attempt](https://github.com/RWTH-EBC/FiLiP/commit/463ab6811f9d47ca48425734a84173a330d33bca).

I have made some progress here. It might be, that this is the correct implementation but now other problems appear. It seems that `SERVICE_PATH` is playing a role. After you change the service path in exercise 4 to something unique and you try to execute exercise 5, you have to have the same service path which makes sense. The following error appears: `requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:4041/iot/devices`.
Interestingly, if you try to execute the same file (exercise 5) again, you get the following error: `pydantic_core._pydantic_core.ValidationError: 1 validation error for list[ServiceGroup]
0.cbHost
Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='None', input_type=str]`. And if you try to execute the file again, the second error keeps appearing. So the first error appears only after single execution and not again. If you want it to appear again, you would need to execute exercise 4 with changed service path.

**Comment by djs0109** [comment]
@WaltherTrgovac  thanks for the contribution! Could you make a pull request (PR) for this branch? We can better discuss the detail implementation or solution under the PR

**Comment by tstorek** [comment]
@WaltherTrgovac `validate_python` is most likely not the function you used. In the newer evrsion of pydantic you need to parse the json yourself and then, e.g. use the `validate_model` function.  If the `*.json` contains a list you need to convert to a list of dicts.

Subseeunetly, you can create a list of models usige e.g. list-comprehension
