### ISSUE TITLE
order in cleanup function

### ISSUE THREAD

**Issue by SBlechmann** [RWTH-EBC/FiLiP#265]
The order in which the cleanup functions are called is important (afaik, only if there is an iot device holding a command).

In the tutorials, the order of the functions called is correct. 
Yet, we just discovered this when calling the functions in a different order, e.g. clear the cb and then the iota, the iota throws an 400 error that the connection to the cb failed.

Maybe we should add this to the docs somewhere?

**Comment by djs0109** [comment]
@SBlechmann could you provide some simple coded for reproducing the error?

**Comment by djs0109** [comment]
@SystemsPurge could you reproduce this error and implement it into a unitest, maybe under `tests/clients/test_ngsi_v2_iota.py`

**Comment by SystemsPurge** [comment]
@djs0109 test is written. Still to see why assertRaises is not catching the HTTPError exception in this case.

**Comment by SystemsPurge** [comment]
@djs0109 Test was not working because it involves clear methods that are subsequently used by the teardown method, so i added a try , except at the teardown but maybe someone should have a better look into that. Should this be pushed to 215?
