### ISSUE TITLE
Specify version of FIWARE stack for tutorials

### ISSUE THREAD

**Issue by djs0109** [RWTH-EBC/FiLiP#277]
**Is your feature request related to a problem? Please describe.**
The behavior of the FIWARE stack is continuously updating. Therefore, to ensure reproducibility, we should add information about the used FIWARE stack, especially their versions.

**Describe the solution you'd like**
- provide a `docker-compose.yml`,
- or reference the https://github.com/N5GEH/n5geh.platform

**Comment by RCX112** [comment]
@djs0109 I am currently testing the compose file on the tutorials, which need to be updated because there is old pydantic code. I will also commit these changes to the branch.
