### ISSUE TITLE
Fix import of Infrastructure Component

### ISSUE THREAD

**Issue by iripiri** [RWTH-EBC/FiLiP#286]
**Description**
Importing of IC fails with no error message in the frontend, the backend returns error 422 "Unprocessable entity", despite using a previously exported IC.

**Comment by djs0109** [comment]
@iripiri thank you for reporting! Could you please describe the context a little bit more, so that we can reproduce the error?

**Comment by iripiri** [comment]
Sorry, this is a bit wild. The issue is for a totally different repository
