### ISSUE TITLE
Requests-Bugfixes

### ISSUE THREAD

**Issue by RedingJeff** [RWTH-EBC/FiLiP#29]
The method post_request does not work, as the http field needs to be in json form:

Current body:
{"provider": {"http": "http://localhost:1234"}, "dataProvided": ...}

Required body:
{"provider": {"http": **{"url":** "http://localhost:1234" **}**, ...}

Further this issue will test if existing registrations are correctly removed (or edited) if the corresponding entity is deleted

**Comment by tstorek** [comment]
@RedingJeff I restructured the models little pleas double check
