### ISSUE TITLE
[JOSS Review] Broken functionality documentation link

### ISSUE THREAD

**Issue by abhishektiwari** [RWTH-EBC/FiLiP#303]
Documentation [link](https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/FiLiP/master/docs/index.html) is broken in `README.md`. Please fix it and provide working link so I can review the docs.

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/6953)

**Comment by djs0109** [comment]
Need to check settings in gitlab-ci.yml:

- [ ] COVERAGE_TYPE
- [ ] EXAMPLE_CONVERTER_CONFIG
- [ ] template links for gitlab-ci pages
- [ ] template links for coverage
- [ ] Update links in readme.md
