### ISSUE TITLE
Expressionlanguage in device should be optional

### ISSUE THREAD

**Issue by djs0109** [RWTH-EBC/FiLiP#312]
**Describe the bug**
Expressionlanguage is not set as optional in the datamodel of `DeviceSettings`, which will cause unexpected validation error

**To Reproduce**
```python
from filip.models.ngsi_v2.iot import Device
test_device = Device.model_validate(  {
    "apikey": "your_apikey",
    "protocol": "IoTA-JSON",
    "transport": "MQTT",
    "expressionLanguage": None,
    "device_id": "device:001",
    "entity_name": "urn:ngsi-ld:WeatherStation:001",
    "entity_type": "WeatherStation",
    "attributes": [
      {
        "name": "sim_time",
        "type": "Number",
        "object_id": "t_sim"
      },
      {
        "name": "temperature",
        "type": "Number",
        "object_id": "t_amb"
      }
    ],
    "ngsiVersion": "v2"
  })

```

**Suggestion**

Use `expressionLanguage: Optional[ExpressionLanguage] = Field(...`, and add a test to prevent this happen again.

**Comment by djs0109** [comment]
Hi @RCX112, could you have a look at this issue?

**Comment by RCX112** [comment]
@djs0109 I can do that. I should set the expressionLanguage to jexl when it is set to None, otherwise it will be set to legacy in older versions of the IoT Agent

**Comment by djs0109** [comment]
@RCX112 Thanks! That sounds good 👍
