### ISSUE TITLE
Function to fetch and refresh tokens

### ISSUE THREAD

**Issue by SBlechmann** [RWTH-EBC/FiLiP#316]
**Is your feature request related to a problem? Please describe.**
Currently, FiLiP only offers a way to handle Bearer tokens in the header but there is no function or example how to fetch (and refresh) a token.
Imo, we should provide a function that does so and adjust the example. 

**Describe the solution you'd like**
Implement our internal functions for the keycloak_token_handler in FiLiP.

**Comment by djs0109** [comment]
Good points. I would integrate it as an example that works for now. There are a lot of third-party libs that can authenticate the session/client/etc, that can be used by FiLiP clients. Therefore, it will be a bit redundant for FiLiP to support and maintain this functionality.
