### ISSUE TITLE
Initial tenant when tenant does not exist

### ISSUE THREAD

**Issue by djs0109** [RWTH-EBC/FiLiP#337]
We need to create a walkaround for LD CB when the tenant is empty. Otherwise, all GET functions will receive an error.

### Solution
We add a check while instantiating the cb client. If the tenant does not exist, we can create a dummy entity and then delete it.

**Comment by SystemsPurge** [comment]
@djs0109 Ok that seems convenient. Despite the fact that , creating a "dummy" entity that happens to already exist is very unlikely, is there actually no other way of creating a tenant ?

**Comment by djs0109** [comment]
@SystemsPurge If the "dummy" entity already exists, the tenant must also exist, so the walkaround should not be triggered. Maybe the cleanest way is to create a reusable error-handling function for capturing the "tenant not found" error. But imop it will cost large effort while bringing little benefit.
