### ISSUE TITLE
Hard coded service path in timeseries test

### ISSUE THREAD

**Issue by sbanoeon** [RWTH-EBC/FiLiP#340]
**Describe the bug**
There is hard coded service path in a quantumleap client test [here](https://github.com/RWTH-EBC/FiLiP/blob/aefa83ecd1b4f3c9a996b217101f2be256983c20/tests/clients/test_ngsi_v2_timeseries.py#L48)

**Expected behavior**
service path should be fetched from the environment file

**Comment by djs0109** [comment]
It is intended to accelerate the test speed
