### ISSUE TITLE
Couldn't update subscription with default values

### ISSUE THREAD

**Issue by dnikolay-ebc** [RWTH-EBC/FiLiP#39]
**Describe the bug**
Method update_subscription of filip.clients.ngsi_v2.ContextBrokerClient has following configuration for request serialization:
```
res = self.patch(
                url=url,
                headers=headers,
                data=subscription.json(exclude={'id'},
                                       exclude_unset=True,
                                       exclude_defaults=True,
                                       exclude_none=True))
```

If a subscription is created/updated with non default values you can never re-set the default ones because defaults are excluded from serialization.

**To Reproduce**

As an example try to update the status of a subscription:

```
        with ContextBrokerClient(url='http://localhost:1026',
                                 fiware_header=FiwareHeader(
                                     service='fw-service',
                                     service_path='/testing',
                                 )) \
                as cb_client:

            subscription = cb_client.get_subscription('xyz')
            subscription.status = Status.INACTIVE

            cb_client.update_subscription(subscription)
```
&#8594; subscription updates status to "inactive"

```
            subscription.status = Status.ACTIVE
            cb_client.update_subscription(subscription)
```

&#8594; subscription still has status "inactive"

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version 20H2
 - Python 3.8

**Comment by dnikolay-ebc** [comment]
update_registration has same issue.

**Comment by tstorek** [comment]
@dnikolay-ebc which version of the library are you currently using?

**Comment by tstorek** [comment]
@dnikolay-ebc 

I tested with a small example:

```python
from pydantic import BaseModel, Field

class Model(BaseModel):
    test: str = Field(default='123')

model = Model(test='123')
print(model.json(exclude_defaults=True))
```

Does indeed skip the default although set, while 
```python
print(model.json(exclude_defaults=False))
```
would do the trick.
I am actually surprised by this behavior of pydantic.

We will correct this as soon as possible.
