### ISSUE TITLE
Support for python 3.9

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/FiLiP#68]
**Is your feature request related to a problem? Please describe.**
Support python 3.9 by dropping support for PyTables.

**Describe the solution you'd like**
Make tables support optional.

**Describe alternatives you've considered**

**Additional context**
https://github.com/PyTables/PyTables/issues/823

**Comment by tstorek** [comment]
@RedingJeff maybe a good solution to remove our hdf would be with csv, but the using datatables to read and write them 
https://towardsdatascience.com/6-pandas-mistakes-that-silently-tell-you-are-a-rookie-b566a252e60d
