### ISSUE TITLE
Failing test: test_add_command_callback_ultralight

### ISSUE THREAD

**Issue by RedingJeff** [RWTH-EBC/FiLiP#91]
**Describe the bug**
The test "test_add_command_callback_ultralight" currently has an approximately 1 in 10 chance to fail when running test in the CI.

**Solution**
Currently the test waits 5 seconds. This seems in the failing cases to be not enough time, therefor the test shall now loop a few times with waits and only fail after multiple retries are failed.

![image](https://user-images.githubusercontent.com/72494333/144584270-565b85ef-faae-4936-8e48-4dddc62e6d06.png)

**Comment by tstorek** [comment]
agreed to accept
