### ISSUE TITLE
Filter commands from get_properties  

### ISSUE THREAD

**Issue by RedingJeff** [RWTH-EBC/FiLiP#92]
The get_properties of the ContextEntity model currently returns all Attributes that do not have the type Relationship.

It should also filter out the commands (cretaed by Fiware).

**Comment by tstorek** [comment]
@djs0109 if you want all attributes you can simply use `get_attributes`. Properties are attribues that describe the object itselft but not its relationships. In ngsi-ld this concept becomes much more clear. 

Relationships should usually not alter over time. If that happens old relationships should be deleted first and new attributes of `type` relationship created. 

Please open a new issue if there is any problem with this.

**Comment by dnikolay-ebc** [comment]
#145
